# Generated by Django 2.1.1 on 2019-01-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duel',
            name='round',
            field=models.SmallIntegerField(choices=[(0, 'Not started'), (1, 'Round 1'), (2, 'Round 2'), (3, 'Round 3'), (4, 'Finished')], default=1, null=True),
        ),
    ]
