# Generated by Django 2.1.1 on 2019-01-19 13:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190118_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(0, 'KNeighborsClassifier'), (1, 'LogisticRegression'), (2, 'LinearSVC'), (3, 'GaussianNB'), (4, 'DecisionTreeClassifier'), (5, 'RandomForestClassifier'), (6, 'GradientBoostingClassifier'), (7, 'MLPClassifier')], max_length=64)),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='duel',
            name='round',
        ),
        migrations.AddField(
            model_name='duel',
            name='rounds',
            field=models.ManyToManyField(to='articles.Algorithm'),
        ),
    ]
