# Generated by Django 2.1.1 on 2019-01-24 12:53

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duels', '0002_auto_20190124_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duel',
            name='user_percentage',
        ),
        migrations.AddField(
            model_name='duel',
            name='user1_percentage',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]), null=True, size=3),
        ),
        migrations.AddField(
            model_name='duel',
            name='user2_percentage',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]), null=True, size=3),
        ),
    ]
