# Generated by Django 2.1.1 on 2019-01-29 11:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duels', '0007_auto_20190128_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAlgorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('0', 'KNeighborsClassifier'), ('1', 'LogisticRegression'), ('2', 'LinearSVC'), ('3', 'GaussianNB'), ('4', 'DecisionTreeClassifier'), ('5', 'RandomForestClassifier'), ('6', 'GradientBoostingClassifier'), ('7', 'MLPClassifier')], max_length=64)),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
